
package at.ac.tuwien.swa.SWAzam.Peer.PeerWebServiceClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PeerWebService", targetNamespace = "http://Peer.SWAzam.swa.tuwien.ac.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PeerWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IdentifyMP3Fingerprint")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "IdentifyMP3Fingerprint", targetNamespace = "http://Peer.SWAzam.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.SWAzam.Peer.PeerWebServiceClient.IdentifyMP3Fingerprint")
    @ResponseWrapper(localName = "IdentifyMP3FingerprintResponse", targetNamespace = "http://Peer.SWAzam.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.SWAzam.Peer.PeerWebServiceClient.IdentifyMP3FingerprintResponse")
    @Action(input = "http://Peer.SWAzam.swa.tuwien.ac.at/PeerWebService/IdentifyMP3FingerprintRequest", output = "http://Peer.SWAzam.swa.tuwien.ac.at/PeerWebService/IdentifyMP3FingerprintResponse")
    public String identifyMP3Fingerprint(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
