
package at.ac.tuwien.swa.SWAzam.Peer.PeerWebServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PeerWebServiceService", targetNamespace = "http://Peer.SWAzam.swa.tuwien.ac.at/", wsdlLocation = "http://localhost:9000/PeerWebService?wsdl")
public class PeerWebServiceService
    extends Service
{

    private final static URL PEERWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PEERWEBSERVICESERVICE_EXCEPTION;
    private final static QName PEERWEBSERVICESERVICE_QNAME = new QName("http://Peer.SWAzam.swa.tuwien.ac.at/", "PeerWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/PeerWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PEERWEBSERVICESERVICE_WSDL_LOCATION = url;
        PEERWEBSERVICESERVICE_EXCEPTION = e;
    }

    public PeerWebServiceService() {
        super(__getWsdlLocation(), PEERWEBSERVICESERVICE_QNAME);
    }

    public PeerWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PEERWEBSERVICESERVICE_QNAME, features);
    }

    public PeerWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, PEERWEBSERVICESERVICE_QNAME);
    }

    public PeerWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PEERWEBSERVICESERVICE_QNAME, features);
    }

    public PeerWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PeerWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PeerWebService
     */
    @WebEndpoint(name = "PeerWebServicePort")
    public PeerWebService getPeerWebServicePort() {
        return super.getPort(new QName("http://Peer.SWAzam.swa.tuwien.ac.at/", "PeerWebServicePort"), PeerWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PeerWebService
     */
    @WebEndpoint(name = "PeerWebServicePort")
    public PeerWebService getPeerWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Peer.SWAzam.swa.tuwien.ac.at/", "PeerWebServicePort"), PeerWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PEERWEBSERVICESERVICE_EXCEPTION!= null) {
            throw PEERWEBSERVICESERVICE_EXCEPTION;
        }
        return PEERWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
