
package at.ac.tuwien.swa.SWAzam.Peer.Peer2ServerConnector.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PeerWebServiceSoap", targetNamespace = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PeerWebServiceSoap {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addCoins", targetNamespace = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.SWAzam.Peer.Peer2ServerConnector.soap.AddCoins")
    @ResponseWrapper(localName = "addCoinsResponse", targetNamespace = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.SWAzam.Peer.Peer2ServerConnector.soap.AddCoinsResponse")
    @Action(input = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/PeerWebServiceSoap/addCoinsRequest", output = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/PeerWebServiceSoap/addCoinsResponse")
    public void addCoins(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns at.ac.tuwien.swa.SWAzam.Peer.Peer2ServerConnector.soap.UserInformation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validateUser", targetNamespace = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.SWAzam.Peer.Peer2ServerConnector.soap.ValidateUser")
    @ResponseWrapper(localName = "validateUserResponse", targetNamespace = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.SWAzam.Peer.Peer2ServerConnector.soap.ValidateUserResponse")
    @Action(input = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/PeerWebServiceSoap/validateUserRequest", output = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/PeerWebServiceSoap/validateUserResponse")
    public UserInformation validateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "reduceCoins", targetNamespace = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.SWAzam.Peer.Peer2ServerConnector.soap.ReduceCoins")
    @ResponseWrapper(localName = "reduceCoinsResponse", targetNamespace = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.SWAzam.Peer.Peer2ServerConnector.soap.ReduceCoinsResponse")
    @Action(input = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/PeerWebServiceSoap/reduceCoinsRequest", output = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/PeerWebServiceSoap/reduceCoinsResponse")
    public void reduceCoins(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0);

}
