
package at.ac.tuwien.swa.SWAzam.Peer.Peer2ServerConnector.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PeerWebServiceSoapService", targetNamespace = "http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/", wsdlLocation = "http://localhost:9000/PeerWebService?wsdl")
public class PeerWebServiceSoapService
    extends Service
{

    private final static URL PEERWEBSERVICESOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException PEERWEBSERVICESOAPSERVICE_EXCEPTION;
    private final static QName PEERWEBSERVICESOAPSERVICE_QNAME = new QName("http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/", "PeerWebServiceSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/PeerWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PEERWEBSERVICESOAPSERVICE_WSDL_LOCATION = url;
        PEERWEBSERVICESOAPSERVICE_EXCEPTION = e;
    }

    public PeerWebServiceSoapService() {
        super(__getWsdlLocation(), PEERWEBSERVICESOAPSERVICE_QNAME);
    }

    public PeerWebServiceSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PEERWEBSERVICESOAPSERVICE_QNAME, features);
    }

    public PeerWebServiceSoapService(URL wsdlLocation) {
        super(wsdlLocation, PEERWEBSERVICESOAPSERVICE_QNAME);
    }

    public PeerWebServiceSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PEERWEBSERVICESOAPSERVICE_QNAME, features);
    }

    public PeerWebServiceSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PeerWebServiceSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PeerWebServiceSoap
     */
    @WebEndpoint(name = "PeerWebServiceSoapPort")
    public PeerWebServiceSoap getPeerWebServiceSoapPort() {
        return super.getPort(new QName("http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/", "PeerWebServiceSoapPort"), PeerWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PeerWebServiceSoap
     */
    @WebEndpoint(name = "PeerWebServiceSoapPort")
    public PeerWebServiceSoap getPeerWebServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Peer2ServerConnector.Server.SWAzam.swa.tuwien.ac.at/", "PeerWebServiceSoapPort"), PeerWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PEERWEBSERVICESOAPSERVICE_EXCEPTION!= null) {
            throw PEERWEBSERVICESOAPSERVICE_EXCEPTION;
        }
        return PEERWEBSERVICESOAPSERVICE_WSDL_LOCATION;
    }

}
