
package at.ac.tuwien.swa.SWAzam.Peer.Peer2PeerConnector.soap;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PeerWebServiceSoap", targetNamespace = "http://Peer2PeerConnector.Peer.SWAzam.swa.tuwien.ac.at/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PeerWebServiceSoap {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod(operationName = "IdentifyMP3Fingerprint")
    @Oneway
    @RequestWrapper(localName = "IdentifyMP3Fingerprint", targetNamespace = "http://Peer2PeerConnector.Peer.SWAzam.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.SWAzam.Peer.Peer2PeerConnector.soap.IdentifyMP3Fingerprint")
    @Action(input = "http://Peer2PeerConnector.Peer.SWAzam.swa.tuwien.ac.at/PeerWebServiceSoap/IdentifyMP3Fingerprint")
    public void identifyMP3Fingerprint(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        List<String> arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "identificationResult", targetNamespace = "http://Peer2PeerConnector.Peer.SWAzam.swa.tuwien.ac.at/", className = "at.ac.tuwien.swa.SWAzam.Peer.Peer2PeerConnector.soap.IdentificationResult")
    @Action(input = "http://Peer2PeerConnector.Peer.SWAzam.swa.tuwien.ac.at/PeerWebServiceSoap/identificationResult")
    public void identificationResult(
        @WebParam(name = "arg0", targetNamespace = "")
        FingerprintResult arg0);

}
